"check_convergence_rrlogit                                               ",&
"cholesky_saxpy                                                          ",&
"compute_center_and_scale_beta_da                                        ",&
"compute_logP_score_Ehess_rrlogit                                        ",&
"compute_logP_score_hess_mstep_rrlogit                                   ",&
"compute_logP_score_hess_rrlogit                                         ",&
"compute_log_proposal_beta                                               ",&
"compute_loglik_logprior_rrlogit                                         ",&
"compute_pi_marg                                                         ",&
"compute_pi_mat_mstep_rrlogit                                            ",&
"compute_pi_mat_rrlogit                                                  ",&
"compute_prior_freq_rrlogit                                              ",&
"compute_rrlogit_predict_se                                              ",&
"compute_scale_rwm                                                       ",&
"compute_start_val_rrlogit                                               ",&
"create_mcmc_objects_rrlogit                                             ",&
"dbeta_R                                                                 ",&
"dbinom_R                                                                ",&
"dbinom_raw_R                                                            ",&
"dbl1_alloc                                                              ",&
"dbl1_dealloc                                                            ",&
"dbl2_alloc                                                              ",&
"dbl2_dealloc                                                            ",&
"dbl3_alloc                                                              ",&
"dbl3dealloc                                                             ",&
"dbl4_alloc                                                              ",&
"dbl4dealloc                                                             ",&
"dchisq_R                                                                ",&
"dgamma_R                                                                ",&
"digamma_R                                                               ",&
"dnbinom_R                                                               ",&
"dnorm_R                                                                 ",&
"dpois_R                                                                 ",&
"dpois_raw_R                                                             ",&
"draw_approx_bayes_beta                                                  ",&
"draw_candidate_beta                                                     ",&
"draw_candidate_beta_rwm                                                 ",&
"dt_R                                                                    ",&
"dunif_R                                                                 ",&
"estep_rrlogit                                                           ",&
"expm1_R                                                                 ",&
"get_integer_table_values                                                ",&
"get_randgen_state_R                                                     ",&
"get_real_table_values                                                   ",&
"get_string_table_values                                                 ",&
"get_table_frequencies                                                   ",&
"get_table_length                                                        ",&
"get_table_type                                                          ",&
"house                                                                   ",&
"householder_ols                                                         ",&
"householder_qr                                                          ",&
"householder_qr2                                                         ",&
"householder_qr2_pivot                                                   ",&
"householder_qr_pivot                                                    ",&
"int1_alloc                                                              ",&
"int1_dealloc                                                            ",&
"int2_alloc                                                              ",&
"int2_dealloc                                                            ",&
"int3_alloc                                                              ",&
"int3_dealloc                                                            ",&
"invert_lower                                                            ",&
"kill_integer_tree                                                       ",&
"kill_real_tree                                                          ",&
"kill_string_tree                                                        ",&
"kronecker                                                               ",&
"kronecker_lower_tri                                                     ",&
"kronecker_symm                                                          ",&
"lgamma1p_R                                                              ",&
"lgamma_R                                                                ",&
"llincgamma                                                              ",&
"llincgamma_d1                                                           ",&
"llincgamma_d2                                                           ",&
"llincgamma_deriv_1                                                      ",&
"llincgamma_deriv_2                                                      ",&
"log1_alloc                                                              ",&
"log1_dealloc                                                            ",&
"log1p_R                                                                 ",&
"log1pexp_R                                                              ",&
"log1pmx_R                                                               ",&
"log2_alloc                                                              ",&
"log2_dealloc                                                            ",&
"log3_alloc                                                              ",&
"log3_dealloc                                                            ",&
"mstep_rrlogit                                                           ",&
"nullify_table                                                           ",&
"nullify_workspace_type_rrlogit                                          ",&
"pbeta_R                                                                 ",&
"pbinom_R                                                                ",&
"pchisq_R                                                                ",&
"pgamma_R                                                                ",&
"pnbinom_R                                                               ",&
"pnorm_R                                                                 ",&
"ppois_R                                                                 ",&
"premult_lower_by_transpose                                              ",&
"pt_R                                                                    ",&
"punif_R                                                                 ",&
"put_data_into_workspace_rrlogit                                         ",&
"put_randgen_state_R                                                     ",&
"qbeta_R                                                                 ",&
"qbinom_R                                                                ",&
"qchisq_R                                                                ",&
"qgamma_R                                                                ",&
"qnbinom_R                                                               ",&
"qnorm_R                                                                 ",&
"qpois_R                                                                 ",&
"qsort_double                                                            ",&
"qsort_integer                                                           ",&
"qsort_integer_A                                                         ",&
"qsort_integer_B                                                         ",&
"qsort_strings                                                           ",&
"qt_R                                                                    ",&
"qunif_R                                                                 ",&
"rbeta_R                                                                 ",&
"rbinom_R                                                                ",&
"rchisq_R                                                                ",&
"rgamma_R                                                                ",&
"rmult_n                                                                 ",&
"rmult_one                                                               ",&
"rnbinom_R                                                               ",&
"rnorm_R                                                                 ",&
"row_house                                                               ",&
"row_house_vec                                                           ",&
"rpois_R                                                                 ",&
"rt_R                                                                    ",&
"run_logit_predict_nonsaturated                                          ",&
"run_logit_predict_saturated                                             ",&
"run_mini_em                                                             ",&
"run_rrlogit                                                             ",&
"run_rrlogit_approx_bayes                                                ",&
"run_rrlogit_da_nonsaturated                                             ",&
"run_rrlogit_da_saturated                                                ",&
"run_rrlogit_em                                                          ",&
"run_rrlogit_em_saturated                                                ",&
"run_rrlogit_fs                                                          ",&
"run_rrlogit_impute                                                      ",&
"run_rrlogit_impute_cond_mean                                            ",&
"run_rrlogit_impute_random                                               ",&
"run_rrlogit_nr                                                          ",&
"run_rrlogit_predict                                                     ",&
"run_rrlogit_rwm_nonsaturated                                            ",&
"runif_R                                                                 ",&
"stack_coef                                                              ",&
"str1_alloc                                                              ",&
"str1_dealloc                                                            ",&
"str2_alloc                                                              ",&
"str2_dealloc                                                            ",&
"str3_alloc                                                              ",&
"str3_dealloc                                                            ",&
"sweep_forward                                                           ",&
"sweep_reverse                                                           ",&
"tabulate_integer_number                                                 ",&
"tabulate_integer_variable                                               ",&
"tabulate_real_number                                                    ",&
"tabulate_real_variable                                                  ",&
"tabulate_string                                                         ",&
"tabulate_string_variable                                                ",&
"trigamma_R                                                              ",&
"unstack_coef                                                            ",&
"write_integer_tree_to_table                                             ",&
"write_real_tree_to_table                                                ",&
"write_string_tree_to_table                                              ",&
